---
driver:
  name: docker
  hostname: galera.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: galera
  grains:
    noservices: True
  dependencies:
    - name: mysql
      repo: git
      source: https://github.com/salt-formulas/salt-formula-mysql.git
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux.git
  state_top:
    base:
      "*":
        - linux
        - galera
  pillars:
    top.sls:
      base:
        "*":
          - versions
          - repos_base
          - repos
          - galera
    versions.sls:
      galera:
        version:
          mysql: <%= ENV['MYSQL_VER'] || '5.6' %>
          galera: <%= ENV['GALERA_VER'] || '3' %>
    # NOTE(vsaienko) There is no guarntee that pillars are loaded before pillars-from-file
    # as result we cant assume variables defined via pillars: are available when pillars-from-file
    # is loaded. Move 'source' definitions of repos to .kitchen.yml as it used ENV variable
    repos_base.sls:
      linux:
        system:
          enabled: true
          repo:
            galeracluster:
              source: deb http://releases.galeracluster.com/galera-<%=ENV['GALERA_VER'] || '3'%>/ubuntu {{ grains.get('oscodename') }} main
            mysql-wsrep:
              source: deb http://releases.galeracluster.com/mysql-wsrep-<%=ENV['MYSQL_VER'] || '5.6'%>/ubuntu {{ grains.get('oscodename') }} main
  pillars-from-files:
    repos.sls: tests/pillar/repo_galeracluster.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: master_cluster
    provisioner:
      pillars-from-files:
        galera.sls: tests/pillar/master_cluster.sls

  - name: slave_cluster
    provisioner:
      pillars-from-files:
        galera.sls: tests/pillar/slave_cluster.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
