{% raw %}
server:
  alert:
    GaleraServiceDown:
      if: >-
        mysql_up != 1
      labels:
        severity: warning
        service: mysql
      annotations:
        summary: 'Galera service down'
        description: 'Galera service is down on node {{ $labels.host }}'
    GaleraNodeNotReady:
      if: 'mysql_wsrep_ready != 1'
      for: 1m
      labels:
        severity: warning
        service: mysql
      annotations:
        summary: 'Galera on {{ $labels.host }} not ready'
        description: 'The Galera service on {{ $labels.host }} is not ready to serve queries.'
    GaleraNodeNotConnected:
      if: 'mysql_wsrep_connected != 1'
      for: 1m
      labels:
        severity: warning
        service: mysql
      annotations:
        summary: 'Galera on {{ $labels.host }} not connected'
        description: 'The Galera service on {{ $labels.host }} is not connected to the cluster.'
{% endraw %}
